version: "3.7"
services:
    gateway:
        image: ${REGISTRY}/auction-gateway:${IMAGE_TAG}
        restart: always
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /var/www/html:/var/www/html:ro
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - frontend
            - api

    frontend:
        build:
            context: frontend/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./frontend:/app

    api:
        build:
            context: api/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./api:/app
        depends_on:
            - api-php-fpm

    api-php-fpm:
        build:
            context: api/docker
            dockerfile: development/php-fpm/Dockerfile
        volumes:
            - ./api:/app
