version: "3.7"
services:
    gateway:
        image: ${REGISTRY}/eventhub-gateway:${IMAGE_TAG}
        restart: always
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /var/www/html:/var/www/html:ro
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - frontend
            - api

    frontend:
        image: ${REGISTRY}/eventhub-frontend:${IMAGE_TAG}
        restart: always

    api:
        image: ${REGISTRY}/eventhub-api:${IMAGE_TAG}
        restart: always
        depends_on:
            - api-php-fpm

    api-php-fpm:
        image: ${REGISTRY}/eventhub-api-php-fpm:${IMAGE_TAG}
        restart: always
        environment:
            APP_DEBUG: 0
            APP_ENV: prod

    api-php-cli:
        image: ${REGISTRY}/eventhub-api-php-cli:${IMAGE_TAG}
        environment:
            APP_DEBUG: 0
            APP_ENV: prod

    api-postgres:
        image: postgres:12.2-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: app
        volumes:
            - api-postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"

volumes:
    api-postgres: