version: "3.7"
services:
    gateway:
        image: ${REGISTRY}/eventhub-gateway:${IMAGE_TAG}
        restart: always
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /var/www/html:/var/www/html:ro
        ports:
            - "80:80"
            - "443:443"

    frontend:
        image: ${REGISTRY}/eventhub-frontend:${IMAGE_TAG}
        restart: always

    api:
        image: ${REGISTRY}/eventhub-api:${IMAGE_TAG}
        restart: always

    api-php-fpm:
        image: ${REGISTRY}/eventhub-api-php-fpm:${IMAGE_TAG}
        restart: always
        environment:
            APP_DEBUG: 0
            APP_ENV: prod
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: ${API_DB_PASSWORD}
            DB_NAME: app
            MAILER_HOST: ${API_MAILER_HOST}
            MAILER_PORT: ${API_MAILER_PORT}
            MAILER_USER: ${API_MAILER_USER}
            MAILER_PASSWORD: ${API_MAILER_PASSWORD}
            MAILER_ENCRIPTION: tls
            MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
            FRONTEND_URL: https://eventhub.1g0rbm.com
            SENTRY_DSN: 'https://5c2750ab20e54b5ea1074f60b8b74159@o479450.ingest.sentry.io/5524360'

    api-php-cli:
        image: ${REGISTRY}/eventhub-api-php-cli:${IMAGE_TAG}
        environment:
            APP_DEBUG: 0
            APP_ENV: prod
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: ${API_DB_PASSWORD}
            DB_NAME: app
            MAILER_HOST: ${API_MAILER_HOST}
            MAILER_PORT: ${API_MAILER_PORT}
            MAILER_USER: ${API_MAILER_USER}
            MAILER_PASSWORD: ${API_MAILER_PASSWORD}
            MAILER_ENCRIPTION: tls
            MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
            FRONTEND_URL: https://eventhub.1g0rbm.com
            SENTRY_DSN: 'https://5c2750ab20e54b5ea1074f60b8b74159@o479450.ingest.sentry.io/5524360'

    api-postgres:
        image: postgres:12.2-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: ${API_DB_PASSWORD}
            POSTGRES_DB: app
        volumes:
            - api-postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"

volumes:
    api-postgres:
