---
-   name: Update apt packages
    apt:
        update_cache: yes

-   name: Remove old certbot packages
    apt:
        name: certbot
        state: absent

-   name: Install Certbot
    apt:
        name: certbot
        state: present
        update_cache: yes

-   name: Copy certbot configuration
    copy:
        src: files/cli.ini
        dest: /etc/letsencrypt/cli.ini
        owner: root
        group: root
        mode: 0644

-   name: Remove useless packages
    apt:
        autoclean: yes

-   name: Remove useless dependencies
    apt:
        autoremove: yes