site:
	ansible-playbook -i hosts.yml site.yml -vvvv

renew-certificates:
	ansible-playbook -i hosts.yml renew-certificates.yml -vvvv

authorize:
	ansible-playbook -i hosts.yml authorize.yml -vvvv

docker-login:
	ansible-playbook -i hosts.yml docker-login.yml -vvvv
